name: weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1

  #state
  get: ^4.6.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1

  #locale
  intl: ^0.17.0

  #store
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #network
  dio: ^4.0.6
  internet_connection_checker: ^0.0.1+4
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master

  cupertino_icons: ^1.0.2

  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true

  assets:
     - assets/